import 'package:flutter/material.dart';

final CurveCollection curves = CurveCollection(
  curveName: _curvesName,
  curves: _curvesCollection,
);

class CurveCollection {
  final List<Curve> curves;
  final List<String> curveName;

  CurveCollection({@required this.curves, @required this.curveName});
}

final List<Curve> _curvesCollection = <Curve>[
  Curves.bounceIn,
  Curves.bounceInOut,
  Curves.bounceOut,
  Curves.decelerate,
  Curves.ease,
  Curves.easeIn,
  Curves.easeInBack,
  Curves.easeInCirc,
  Curves.easeInCubic,
  Curves.easeInExpo,
  Curves.easeInOut,
  Curves.easeInOutBack,
  Curves.easeInOutCirc,
  Curves.easeInOutCubic,
  Curves.easeInOutExpo,
  Curves.easeInOutQuad,
  Curves.easeInOutQuart,
  Curves.easeInOutQuint,
  Curves.easeInOutSine,
  Curves.easeInQuad,
  Curves.easeInQuart,
  Curves.easeInQuint,
  Curves.easeInSine,
  Curves.easeInToLinear,
  Curves.easeOut,
  Curves.easeOutBack,
  Curves.easeOutCirc,
  Curves.easeOutCubic,
  Curves.easeOutExpo,
  Curves.easeOutQuad,
  Curves.easeOutQuart,
  Curves.easeOutQuint,
  Curves.easeOutSine,
  Curves.elasticIn,
  Curves.elasticInOut,
  Curves.elasticOut,
  Curves.fastLinearToSlowEaseIn,
  Curves.fastOutSlowIn,
  Curves.linear,
  Curves.linearToEaseOut,
  Curves.slowMiddle,
];

final List<String> _curvesName = <String>[
  "Curves.bounceIn",
  "Curves.bounceInOut",
  "Curves.bounceOut",
  "Curves.decelerate",
  "Curves.ease",
  "Curves.easeIn",
  "Curves.easeInBack",
  "Curves.easeInCirc",
  "Curves.easeInCubic",
  "Curves.easeInExpo",
  "Curves.easeInOut",
  "Curves.easeInOutBack",
  "Curves.easeInOutCirc",
  "Curves.easeInOutCubic",
  "Curves.easeInOutExpo",
  "Curves.easeInOutQuad",
  "Curves.easeInOutQuart",
  "Curves.easeInOutQuint",
  "Curves.easeInOutSine",
  "Curves.easeInQuad",
  "Curves.easeInQuart",
  "Curves.easeInQuint",
  "Curves.easeInSine",
  "Curves.easeInToLinear",
  "Curves.easeOut",
  "Curves.easeOutBack",
  "Curves.easeOutCirc",
  "Curves.easeOutCubic",
  "Curves.easeOutExpo",
  "Curves.easeOutQuad",
  "Curves.easeOutQuart",
  "Curves.easeOutQuint",
  "Curves.easeOutSine",
  "Curves.elasticIn",
  "Curves.elasticInOut",
  "Curves.elasticOut",
  "Curves.fastLinearToSlowEaseIn",
  "Curves.fastOutSlowIn",
  "Curves.linear",
  "Curves.linearToEaseOut",
  "Curves.slowMiddle",
];
